// AUTO-GENERATED by scripts/gen-promo-timings.mjs — do not edit by hand.
// Scene durations (seconds) + phrase marks (frames, scene-relative) locked to
// the narration take (49.78s total).
export const FPS = 30;
export const NARRATION_SECONDS = 49.78;
export const SCENES = [
  {
    "k": "hook",
    "s": 10.36,
    "marks": {
      "sub": 88,
      "reveal": 225
    }
  },
  {
    "k": "continuity",
    "s": 11.49,
    "marks": {
      "chip": 199
    }
  },
  {
    "k": "verify",
    "s": 8.44,
    "marks": {
      "chip": 207
    }
  },
  {
    "k": "ease",
    "s": 7.91,
    "marks": {
      "chip": 201
    }
  },
  {
    "k": "outcome",
    "s": 6.97,
    "marks": {
      "chip": 116
    }
  },
  {
    "k": "cta",
    "s": 4.62,
    "marks": {
      "btn": 32,
      "url": 118
    }
  }
] as const;
export type SceneKey = typeof SCENES[number]['k'];
